src/nycpython/apps/events/urls.py
from django.conf.urls.defaults import *
from nycpython.apps.events.models import Event
from nycpython.apps.events.feeds import LatestEventFeed

urlpatterns = patterns('nycpython.apps.events.views',
                       url(r'^$', 'event_index', name='event_index'),
                       url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', 'event_detail', name='event_detail',),
                       )

feeds = {
    'latest-events': LatestEventFeed,
         }

urlpatterns += patterns('',
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
                        )

src/nycpython/apps/meetup/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('nycpython.apps.meetup.views',
                        url(r'^login/', 'begin_login', name='meetup_login'),
                        url(r'^logout/', 'logout', name='meetup_logout'),
                        url(r'^confirm/', 'confirm', name='meetup_login_confirm'),
                        url(r'^test/', 'test', name='meetup_test'),
                       )

src/nycpython/urls.py
from django.conf.urls.defaults import *
from django.http import HttpResponse
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
     (r'^admin/', include(admin.site.urls)),
    url(r'^$', 'nycpython.views.index'), 
    url(r'^events/', include('nycpython.apps.events.urls')),
    url(r'^meetup/', include('nycpython.apps.meetup.urls')),
    url(r'^topics/', include('topics.urls')),
    url(r'freenode32gf56gd.ver', lambda x: HttpResponse('hi freenode')),
)

if settings.LOCAL_DEVELOPMENT:
    static_url = settings.LOCAL_MEDIA_URL.lstrip('/')
    urlpatterns += patterns("django.views",
        url(r"^%s(?P<path>.*)$" % static_url, "static.serve", {
            "document_root": settings.MEDIA_ROOT,
        }),
    )
    static_url = settings.ADMIN_MEDIA_PREFIX.lstrip('/')

src/nycpython/apps/events/models.py
import datetime

from django.db import models

from nycpython.apps.events.managers import EventManager

from nycpython.lib.managers import get_live_manager

class Event(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    published = models.BooleanField(default=False)
    date = models.DateField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    description_html = models.TextField(null=True, blank=True)
    doors_time = models.TimeField(null=True, blank=True)
    start_time = models.TimeField(null=True, blank=True)
    #host = models.ForeignKey('organizations.Organization', null=True, blank=True)
    directions = models.TextField(null=True, blank=True)
    last_meetup_update = models.DateTimeField(null=True, blank=True)
    meetup_id = models.CharField(max_length=50, null=True, blank=True)
    yes_rsvps = models.IntegerField(default=0)
    no_rsvps = models.IntegerField(default=0)
    maybe_rsvps = models.IntegerField(default=0)
    num_attendees = models.IntegerField(default=0)

    objects = EventManager()
    live = get_live_manager(EventManager)()

    class Meta:
        ordering = ['-date']

    def __unicode__(self):
        return "%s on %s" % (self.title, self.date)

    #@models.permalink
    def get_absolute_url(self):
        return "http://www.meetup.com/nycpython/calendar/%s/" % self.meetup_id
        return ('event_detail', (), { 'year' :self.date.year, 'month' :  self.date.month, 'day' : self.date.day })

    def get_previous_published(self):
        try:
            return self.get_previous_by_date(published=True)
        except Event.DoesNotExist:
            return None

    def get_next_published(self):
        try:
            return self.get_next_by_date(published=True)
        except Event.DoesNotExist:
            return None

    @property
    def remaining_slots(self):
        # Information not provided by meetup's API
        return 0

src/nycpython/apps/meetup/models.py
from django.db import models

from nycpython.lib.models import BaseModel

from nycpython.apps.meetup.client import MeetupClient


class MeetupProfile(BaseModel):
    user = models.OneToOneField('auth.User', related_name='meetup')
    meetup_id = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    photo_url = models.CharField(max_length=200)
    bio = models.TextField(max_length=600)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=2)
    access_key = models.CharField(max_length=32)
    secret_key = models.CharField(max_length=32)

    def get_client(self):
        return MeetupClient(self.access_key, self.secret_key)

    def get_absolute_url(self):
        return "http://www.meetup.com/members/%s/" % (self.meetup_id,)

src/nycpython/lib/models.py
from django.db import models

class BaseModel(models.Model):
    created_on = models.DateTimeField(blank=True, null=True, editable=False)
    created_by = models.ForeignKey('auth.User', blank=True, null=True, editable=False)
    updated_on = models.DateTimeField(blank=True, null=True, editable=False)
    created_by = models.ForeignKey('auth.User', blank=True, null=True, editable=False)

    class Meta:
        abstract = True

src/nycpython/apps/events/views.py
from nycpython.apps.events.models import Event
from nycpython.lib.decorators import render_to

@render_to('events/event_index.html')
def event_index(request):
    event_list = Event.objects.all().filter(published=True).order_by('-date')
    upcoming_events = Event.live.get_upcoming_events()
    past_events = Event.live.get_past_events()

    return {'upcoming_events' : upcoming_events,
            'past_events' : past_events,
            'active_menu': 'Events'}


@render_to('events/event_detail.html')
def event_detail(request, year, month, day ):
    year, month, day = int(year), int(month), int(day)
    event = Event.objects.get(
        published = True,
        date__year = year,
        date__month = month,
        date__day = day,
        )
    #previous_event = event.get_previous_published()
    #next_event = event.get_next_published()
    return {
            'event': event,
            #'previous_event': previous_event,
            #'next_event': next_event,
        }

src/nycpython/apps/meetup/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth import login, authenticate

from nycpython.apps.meetup.client import get_auth_url, confirm_auth

from nycpython.lib.decorators import render_to

@render_to('meetup/login.html')
def begin_login(request):
    authorize_url, request_secret = get_auth_url('http://' + request.META['HTTP_HOST'] + '/meetup/confirm/')
    request.session['request_secret'] = request_secret
    return {'authorize_url' : authorize_url }

def confirm(request):
    request_key = request.GET['oauth_token']
    request_secret = request.session['request_secret']
    verifier =  request.GET['oauth_verifier']
    client = confirm_auth(request_key, request_secret, verifier)
    member = client.get_profile()
    user = authenticate(member=member, access_key=client.access_key, access_secret=client.access_secret)
    if not user.is_anonymous():
        login(request, user)
    return HttpResponseRedirect('/')

def logout(request):
    from django.contrib.auth import logout
    logout(request)
    return HttpResponseRedirect('/')


@render_to('meetup/test.html')
def test(request):
    client = request.user.meetup.get_client()
    member = client.get_profile()
    return {'member' : member }

src/nycpython/views.py
from nycpython.apps.events.models import Event
from nycpython.lib.decorators import render_to

@render_to('index.html')
def index(request):
    upcoming_event = Event.live.get_upcoming_events()[:1]
    if upcoming_event:
        upcoming_event = upcoming_event[0]
        
    past_events = Event.live.get_past_events()[:5]
    return { 'upcoming_event' : upcoming_event,
             'past_events'    : past_events }

src/nycpython/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <title>{% block title %}{% endblock %} | NYC Python</title>
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/reset.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/960.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/global.css" type="text/css" media="screen" />
    {% block extra_style %}
    {% endblock %}
	<script type="text/javascript" src="/media/js/jquery-1.4.1.min.js"></script>
    {% block extra_js %}
    {% endblock %}
  </head>
  <body>
    <div class="container_12">
      <div class="grid_9">
        &nbsp;
      </div>
      <div class="grid_3 user_area">
        {% comment %}
        {% if user.is_anonymous %}
        <p> <a href="{% url meetup_login %}">Login via meetup</a></p>
        {% else %}
        <p><a href={{user.meetup.get_absolute_url}}>{{user.meetup.name}}</a> | <a href="{% url meetup_logout %}">Log out</a></p>
        {% endif %}
        {% endcomment %}
      </div>
    </div>
    <div id="masthead">
      <div class="container_12">
        <h1 id="logo"><a href="/"><img src="{{ MEDIA_URL }}images/nyc_python_logo.png"></a></h1>
        {% comment %}
        NYC is chunkfive and python is in futura with the pycon
        logo as the o. Would be nice to bring the skyline into it
        somehow.
        {% endcomment %}
        <p>Your connection to the New York City the python community.</p>
      </div>
    </div>

    <div class="container_12">

      <!-- <ul id="nav"> -->
      <!--   <li class="selected"><a href="#">home</a></li> -->
      <!--   <li><a href="#">archives</a></li> -->
      <!--   <li><a href="#">organizations</a></li> -->
      <!--   <li><a href="#">presentations</a></li> -->
      <!-- </ul> -->

      <div id="content">
        {% block body %}{% endblock %}
      </div>
      <div id="footer">
        <hr />
      </div>
    </div>
    {% block footer %}
    {% endblock %}
  </body>
</html>

src/nycpython/templates/events/event_detail.html
{% extends "base.html" %}

{% block title %} Event on {{ event.date|date:"l, F jS, Y" }} {% endblock %}

{% block body %}
<h1>{{event.title}}</h1>

{{ event.location }} on {{ event.date|date:"l, F jS, Y" }}

<h3>Details</h3>

<ul>
  <li>Date: {{ event.date|date:"l, F jS, Y" }}</li>
  <li>Time: {{ event.time }}</li>
  <li>Location: {% if event.location_url %}
    <a href="{{ event.location_url }}">{{ event.location }}</a> 
    {% else %}
    {{ event.location }}
    {% endif %}
  </li>
  {% if event.map_url %}<li><a href="{{ event.rsvp_url }}">Map</a></li>{% endif %} 
  {% if event.rsvp_url %}<li><a href="{{ event.rsvp_url }}">RSVP</a></li>{% endif %} 

</ul>

<h3>Description</h3>

{{ event.general_description_html }}

<h3>Presentations</h3>

<ul>
  {% for presentation in event.associated_presentations %}
  <li><a href="{{ presentation.get_absolute_url }}">{{ presentation.title }}</a> 
    {{ presentation.description_html }}

    <br />By: 
    {% for speaker in presentation.speaker.all %}


{% if speaker.personal_page %}<a href="{{ speaker.get_absolute_url }}">{{ speaker.full_name }}</a>
{% else %}
{{ speaker.full_name }}{% endif %}{% if not forloop.last %},{% else %}{% endif %}

  </li>
  {% endfor %}

</ul>

{% endfor %}

{% endblock %}

src/nycpython/templates/events/event_index.html
{% extends "base.html" %}
{% load markup %}

{% block title %} NYC Python: Events {% endblock %}

{% block hlt-events %}
<li class="selected"><a href="">Events</a></li>
{% endblock %}

{% block middle-column-full-box %}

<div class="middle-column-box-title-grey">
<font style="text-transform: capitalize;">
Events
</font>
</div>

        {% for event in event_list %}
              <p>
	      <a href="{{ event.get_absolute_url }}"><b>{{ event.location }} on {{ event.date|date:"l, F jS, Y" }}</b></a><br>
	      {{ event.general_description_html|markdown }}
	      
              </p>
        {% endfor %}

{% endblock %}

src/nycpython/templates/events/feeds/feed_description.html
{% load markup %}

<h3>Details</h3>

<ul>
  <li>Date: {{ obj.date|date:"l, F jS, Y" }}</li>
  <li>Time: {{ obj.time }}</li>
  <li>Location: {% if obj.location_url %}
    <a href="{{ obj.location_url }}">{{ obj.location }}</a> 
    {% else %}
    {{ obj.location }}
    {% endif %}
  </li>
  {% if obj.map_url %}<li><a href="{{ obj.rsvp_url }}">Map</a></li>{% endif %} 
  {% if obj.rsvp_url %}<li><a href="{{ obj.rsvp_url }}">RSVP</a></li>{% endif %} 

</ul>


{{ obj.general_description_html|markdown }}

src/nycpython/templates/events/feeds/feed_title.html
{{ obj }}

src/nycpython/templates/index.html
{% extends "base.html" %}
{% block title %} NYC Python {% endblock %}

{% block body %}
<div id="upcoming" class="alpha grid_9">
  {% if upcoming_event %}
  <h3>Next Meeting</h3>
  <div class="meeting"><h4><a href="{{upcoming_event.get_absolute_url}}">{{upcoming_event.title}} - {{upcoming_event.date|date}} @ {{upcoming_event.start_time|time}}</a></h4>
    <p>{{ upcoming_event.description|safe|truncatewords_html:300 }} </p>
  </div>
  <div class="call-to-action">
    <p>Can you be there?</p>
    {# <p><span class="yes-rsvps">{{upcoming_event.yes_rsvps}}</span> people said yes so far - <span class="spots-remaining">{{upcoming_event.remaining_slots}}</span> spots left.</p> #}
    <p><a href="{{ upcoming_event.get_absolute_url }}">RSVP Now!</a></p>
  </div>
  {% else %}
  <p>No next event is schedule yet.  <a href="http://www.meetup.com/nycpython/">Join the group</a> to get notified when one is scheduled </p>
  {% endif %}
</div>
<div id="archives" class="omega grid_3">
  <h3>Past Meetings</h3>
  <ul>
    {% for event in past_events %}
    <li>
      <div class="month">{{event.date|date:"F"}}</div>
      <a href="{{ event.get_absolute_url }}">{{ event.title }}</a>
    </li>
    {% endfor %}
  </ul>
  <a href="http://www.meetup.com/nycpython/calendar/past_list/">See all past meetups</a>
  {% endblock %}

src/nycpython/templates/meetup/login.html
{% extends "base.html" %}
{% block body %}
Go to <a href="{{authorize_url}}">meetup.com</a> to authorize nycpython.org.
{% endblock %}

src/nycpython/templates/meetup/test.html
{% extends "base.html" %}
{% block body %}
<p>You are logged in as {{ member.name }}.</p>
{% endblock %}

src/nycpython/templates/topics/includes/no_topics.html
<div id="notopics">
    <form action="{% url create_topic %}" method="POST">
        {% csrf_token %}
        <p><input type="hidden" name="title" value="{{search_term}}"></input></p>
        <p><b>Would you like to suggest this topic?</b></p>
        <p><input id="volunteer" name="volunteer" type="checkbox">Check here to volunteer to present on this topic (you can do this later)</input></p>
        <input id="create" type="submit" value="Suggest">
        <h3>No topics found</h3>
        <p>No topics matched your search.</p>
    </form>
</div>

src/nycpython/templates/topics/includes/search_form.html
{{form.title}}

src/nycpython/templates/topics/includes/topic_item.html
{% load topics_tags %}
<div class="container_10 clearfix topic">
    <div class="grid_2">
        <p class="vote_count" id="vote_count_{{topic.id}}">{{topic.votes}}</p>
        {% if has_voted %}
        <p class="voted">Voted</p>
        {% else %}
        <p><form action="{% url topic_vote topic.id %}" method="post">{% csrf_token %}<input type="submit" value="vote" class="vote_up" id="vote_up_{{topic.id}}"></form></p>
        {% endif %}
    </div>
    <div class="grid_6">
        <a href="{{topic.get_absolute_url}}">{{topic.title}}</a>
        <div class="description">{{topic.description}}</div>
        <p><div class="byline">Suggested by {% render_topic_user topic.creator %}
            {% if presenter %}
            <span class="presenter">(Has presenter)</span>
            {% else %}
            <span class="presenter">(No presenter - volunteer!)</span>
            {% endif %}
        </div>
    </div>
</div>

src/nycpython/templates/topics/includes/user.html
<a href="">{{user.meetup.name}}</a>

src/nycpython/templates/topics/index.html
{% extends "base.html" %}
{% block extra_style %}
    <link rel="stylesheet" href="/media/topics/css/text.css">
    <link rel="stylesheet" href="/media/topics/css/colorbox.css">
    <link rel="stylesheet" href="/media/topics/css/style.css">
{% endblock %}
{% block extra_js %}
    <script type="text/javascript" src="/media/topics/js/edit.js"></script>
    <script type="text/javascript" src="/media/topics/js/jquery.colorbox-min.js"></script>
{% endblock %}
{% load topics_tags %}
{% block body %}
<form id="search_form" action="" method="GET">
{% render_topic_search_form search_term %}
</form>
{% if topics %}
    <div id="search_results">
        <div id="topic_list">
            {% if topics %}
                {% render_topic_list topics %}
            {% else %}
                {% render_no_topic_matches search_term %}
            {% endif %}
        </div>
    </div>
{% else %}
{% endif %}
{% endblock %}

{% block footer %}
{{block.super}}
<script type="text/javascript">

var create_topic_done = function(res, status) {
  if (status == "success") {
    var data = eval("(" + res.responseText + ")");
    update_search();
    display_success(data["msg"], $("#id_title"));
  }
  else {
    display_error(res.responseText, $("#id_title"));
  }
  return false;
}


var create_topic = function() {
  var title = $("#id_title").val()
  if (title != "" ) {
    var data = { title:title };
    if($('#volunteer').is(':checked')) {
        data['volunteer'] = 1;
    }
    var args = { type:"POST", url:"{% url create_topic %}", data:data, complete:create_topic_done };
    $.ajax(args);
  }
  else {
    display_error("Please enter a topic.", $("#id_title"));
  }
  return false;
};

var vote_done = function(res, status, topic_id) {
    if (status == "success") {
	var data = eval("(" + res.responseText + ")");
	votes = data['score']['score'];
	$("#vote_count_"+topic_id).html(votes);
	$("#vote_up_"+topic_id).html("Voted");
        return false;
    }
    else {
	display_error(res.responseText, $(".vote"));
    }
}

var add_vote = function() {
    topic_id = $(this).attr('id').substring(8);

    $.ajax({
	type: "POST",
	data: {HTTP_X_REQUESTED:'XMLHttpRequest'},
	url: "{{request.META.SCRIPT_NAME}}/topics/" + topic_id + "/vote",
	complete: function(res, status) {return vote_done(res, status, topic_id);}
    });
    return false;
};

var search_done = function(res, status) {
    if (status == "success") {
        $("#topic_list").html(res.responseText);
	$(".vote_up").click(add_vote);
    }
    else {
	display_error(res.responseText, $("#id_title"));
    }
}


var update_search = function() {
    $("#topic_list").html("Loading topics...");
    var title = $("#id_title").val();
    $.ajax({
	type: "GET",
	data: {"title" : title },
	url: "{% url topic_search %}",
	complete: search_done
    });
}


$(document).ready(function() {
{% if user.is_authenticated %}
$("#create").click(create_topic);
$(".vote_up").click(add_vote);
{% else %}
$("#create").colorbox({inline:true, href:"#reg_popup", transition: "fade"})
$(".vote_up").colorbox({inline:true, href:"#reg_popup", transition: "fade"})
{% endif %}
$("#id_title").keyup(update_search);
update_search();
})
</script>
{% endblock %}